### ISSUE TITLE
zarr ingest

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#1063]
i triggered zarr ingest on a small set of 9 files. it ingested 4 and stopped (i think). didn't see any other files ingested.

https://dandiarchive.org/dandiset/000108/draft/files?location=sub-MITU01%2Fses-20210521h17m17s06%2Fmicr%2F

it would be good to know how to determine what succeeded and failed.

on a related note, the zarr ingest end point requires a zarr id in both the api url and as a payload for the post. shouldn't one be sufficient?

**Comment by satra** [comment]
perhaps another related issue. this is on a previously ingested file.

```
$ dandi upload sub-MITU01_ses-20210521h17m17s06_sample-178_stain-LEC_run-1_chunk-2_SPIM.ngff
2022-04-26 14:27:45,953 [    INFO] Found 1 files to consider
PATH                                                                                      SIZE    ERRORS UPLOAD STATUS                          MESSAGE                                                                
...s06/micr/sub-MITU01_ses-20210521h17m17s06_sample-178_stain-LEC_run-1_chunk-2_SPIM.ngff 52.5 GB   0           ERROR                           Error 400 while sending POST request to https://api.dandiarchive.org...Summary:                                                                                  52.5 GB               1 ERROR                         1 Error 400 while sending POST request to https://api.dandiarchive.o...
2022-04-26 14:50:35,571 [    INFO] Logs saved in /home/satra/.cache/dandi-cli/log/20220426182704Z-662907.log
```

and 

```
2022-04-26T14:50:35-0400 [DEBUG   ] urllib3.connectionpool 662907:140131214083840 https://api.dandiarchive.org:443 "POST /api/zarr/2fe1afcb-bc07-44e7-8a9e-cd2337320163/ingest/ HTTP/1.1" 400 31
2022-04-26T14:50:35-0400 [DEBUG   ] dandi 662907:140131214083840 Response: 400
2022-04-26T14:50:35-0400 [ERROR   ] dandi 662907:140131214083840 Error 400 while sending POST request to https://api.dandiarchive.org/api/zarr/2fe1afcb-bc07-44e7-8a9e-cd2337320163/ingest/: "Zarr archive already ingested"
2022-04-26T14:50:35-0400 [ERROR   ] dandi 662907:140131214083840 Error uploading /mnt/beegfs/Lee/dandi/sub-MITU01/ses-20210521h17m17s06/micr/sub-MITU01_ses-20210521h17m17s06_sample-178_stain-LEC_run-1_chunk-2_SPIM.ngff:
Traceback (most recent call last):
  File "/mnt/beegfs/satra/miniconda3/envs/dandi/lib/python3.8/site-packages/dandi/upload.py", line 232, in process_path
    for r in dfile.iter_upload(
  File "/mnt/beegfs/satra/miniconda3/envs/dandi/lib/python3.8/site-packages/dandi/files.py", line 987, in iter_upload
    client.post(f"/zarr/{zarr_id}/ingest/")
  File "/mnt/beegfs/satra/miniconda3/envs/dandi/lib/python3.8/site-packages/dandi/dandiapi.py", line 279, in post
    return self.request("POST", path, **kwargs)
  File "/mnt/beegfs/satra/miniconda3/envs/dandi/lib/python3.8/site-packages/dandi/dandiapi.py", line 245, in request
    raise requests.HTTPError(msg, response=result)
requests.exceptions.HTTPError: Error 400 while sending POST request to https://api.dandiarchive.org/api/zarr/2fe1afcb-bc07-44e7-8a9e-cd2337320163/ingest/
```

**Comment by waxlamp** [comment]
@AlmightyYakob, @mvandenburgh: can we cook up a test case that deliberately causes zarr processing to fail? Even if it's not part of the unit/integration test suite, it would be useful to be able to run a simulated failure live on a dev instance precisely for bugfixing like this.

But this might be trickier than just "making it fail in a test"--the failures we see in prod are somewhat byzantine, at least in the sense that we don't have sufficient logging around these error conditions, putting us in "unknown unknown" territory.

We may need to meet to discuss this, because it likely will involve a lot of code reading/understanding to figure out a model for what is happening. I'll set something up.

**Comment by danlamanna** [comment]
> it would be good to know how to determine what succeeded and failed.

I believe this is now possible via the listing endpoint. @AlmightyYakob can you confirm?

> on a related note, the zarr ingest end point requires a zarr id in both the api url and as a payload for the post. shouldn't one be sufficient?

This shouldn't be the case since #1448.

**Comment by AlmightyYakob** [comment]
> > it would be good to know how to determine what succeeded and failed.
> 
> I believe this is now possible via the listing endpoint. @AlmightyYakob can you confirm?

If the question is "can you tell what files are mismatched if a zarr upload fails" then yes, although I'm not sure that's the question being asked, since there are 9 separate zarrs in the linked folder (see [here](https://api.dandiarchive.org/api/dandisets/000108/versions/draft/assets/?glob=sub-MITU01%2Fses-20210521h17m17s06%2F*.zarr&metadata=false)).
> > on a related note, the zarr ingest end point requires a zarr id in both the api url and as a payload for the post. shouldn't one be sufficient?
> 
> This shouldn't be the case since #1448.

Indeed the new `finalize` endpoint takes no payload, just path arguments.

**Comment by waxlamp** [comment]
@satra, since the Zarr upload process has undergone some serious improvement, I'm going to close this as completed and leave it to you to re-open if you are still observing the same problem you reported originally.
