### ISSUE TITLE
Some checksums aren't committing in time

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1156]
```
2022-07-03T06:35:18-0400 [ERROR   ] backups2datalad: Dandiset 000288: sub-H19.03.316/sub-H19.03.316_ses-914342344_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-07-03T06:35:18-0400 [ERROR   ] backups2datalad: Dandiset 000288: sub-H19.03.316/sub-H19.03.316_ses-912201092_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-07-03T06:35:19-0400 [ERROR   ] backups2datalad: Dandiset 000288: sub-H19.03.316/sub-H19.03.316_ses-914257522_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-07-03T06:35:28-0400 [ERROR   ] backups2datalad: Job failed on input <Dandiset 000288/draft>:
Traceback (most recent call last):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/aioutil.py", line 189, in dowork
    outp = await func(inp)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 129, in update_dandiset
    changed = await self.sync_dataset(dandiset, ds, dlog)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 152, in sync_dataset
    await syncer.sync_assets()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/syncer.py", line 37, in sync_assets
    self.report.check()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/util.py", line 70, in check
    raise RuntimeError(
RuntimeError: Errors occurred while downloading: 3 assets on server had no SHA256 hash despite advanced age
```
Needs checking/fixing

**Comment by waxlamp** [comment]
@AlmightyYakob, is this related to your recent fix of launching checksum calculations as separate tasks? If so, then I think we need a way for clients to keep track of those extra tasks and when they complete.

**Comment by AlmightyYakob** [comment]
I'm not sure, but I doubt it, seems like something else went wrong. @yarikoptic, do you know the sizes of these assets?

**Comment by yarikoptic** [comment]
> @yarikoptic, do you know the sizes of these assets?

I know only  as much as was stated, but we could check, e.g.

```shell
$> dandi ls dandi://dandi/000288@draft/sub-H19.03.316/sub-H19.03.316_ses-914342344_icephys.nwb
- asset_id: 0d7724de-65fe-447d-ae17-ffaed6306eaa
  blob: 486caf5e-6382-46cd-a5ab-6a4cd23c9510
  created: '2022-07-01T22:39:06.989063+00:00'
  modified: '2022-07-01T22:39:07.842331+00:00'
  path: sub-H19.03.316/sub-H19.03.316_ses-914342344_icephys.nwb
  size: 40190924
```

so seems "tiny" (~40MB) in this particular csae

**Comment by AlmightyYakob** [comment]
Hmm, I've found that asset blob in the database. From what I'm seeing, there's a sha256 there, and as you can see in the code snippet you sent (I also found this value independently), the last modified time is `2022-07-01T22:39:07.803650+00:00` UTC time, which is a second after it was created. So it seems the task was immediately picked up and finished. 

I'm not sure how the CLI `ls` command operates, but I don't see how it would be querying for this sha256 value? The only place I can see this value returned is in the `POST /blobs/digest` endpoint, which requires the sha256 value anyway, and returns the assetblob. Using the sha256 I found in the backend on this endpoint returns an asset blob serialization that matches the `blob_id` of what you originally posted:

```
{
  "blob_id": "486caf5e-6382-46cd-a5ab-6a4cd23c9510",
  "etag": "734c031e14b6b308e0dc13af9befd4e4-1",
  "sha256": "eb08125699c0539546bcb101568a2d9641eef28e42cf5762593439929128b77e",
  "size": 40190924
}
```

So maybe there's an issue in retrieval?

**Comment by yarikoptic** [comment]
it should be also populated in `.metadata.digests` field which typically has dandi-etag **and** sha2-256.  But it is not there for some of the assets in that folder  (sorry - my `jq`-foo is too basic for this, here comes `grep`):

```shell
$> dandi ls -r -f json_pp --metadata assets dandi://dandi/000288@draft/sub-H19.03.316/ | grep -e '_id' -e 'sha' 
2022-07-05 15:26:09,745 [ WARNING] A newer version (0.43.0) of dandi/dandi-cli is available. You are using 0.39.6+32.g9f82246
    "asset_id": "91e632dc-38bb-42fc-89a5-96c7f7d23443",
        "dandi:sha2-256": "a850ad3d292a6f3cb4c005c0354021ba1bb2a6f0c18023ee629899bf1627a7a5"
    "asset_id": "7e6ac6b2-6986-4ea2-9f26-eab1bf910a20",
        "dandi:sha2-256": "19cf2b371f371f69051b12e420e244ac64cf6b46c5b6a92529f95d9039e2dde8"
    "asset_id": "0d7724de-65fe-447d-ae17-ffaed6306eaa",
    "asset_id": "0f06441a-6b45-4df0-acdf-8bd4143fa948",
    "asset_id": "a2742a68-14ad-4547-a281-98ba61cb389f",
        "dandi:sha2-256": "4431a74758e1cda4f7f1b441fdc564a2b9dfa289b5c3853300e3f2ae8bec1032"
    "asset_id": "fab14a7c-49dc-4088-8f94-28fdde2666ea",
        "dandi:sha2-256": "33850cb310b06265ebfb61fc3a5e6c589a5004a060f55f1c0ac465898d678dc9"
    "asset_id": "1bfc6cc3-5638-483f-b012-6e67980f185a",
        "dandi:sha2-256": "5dbab4923b796d8bae47d99ad2a7d994e52d4a04cd3ad2fdb776de8da81e476e"
    "asset_id": "9f74c8ec-41fa-4067-b386-b79c0ec59e94",
        "dandi:sha2-256": "49289f8457c396af5bd8db5de670bffcc4f912f934ddd5a9dcd3154e4b9cbb6f"
    "asset_id": "3e8fb7d0-552c-4f94-a126-8ec28a988a0a",
        "dandi:sha2-256": "42461aa7c881957bc596e7686ae21b23dd9b81fe57eafed769b1a88a9cf5bc32"
    "asset_id": "80f29b45-501c-480a-a046-dcde0a9f95d4",
        "dandi:sha2-256": "98ded2b3df3c8f03ce944ed31d4d8d3c012187a2a12bccac3fdb7a88e71f4742"
    "asset_id": "abbe295c-77f5-42bf-9b18-5544e8b9e36d",
        "dandi:sha2-256": "530dc266eac93ce815a30b7640320ec1139633f016aeb61fd83c973e45060b36"
    "asset_id": "3c0fa185-8d17-4f9d-96e3-811490c28527",
        "dandi:sha2-256": "f168007355c5833b08a7766e3e03642a2b644dc6e0c7576bc3a3ac49ca2ac47e"
    "asset_id": "bdf6565c-2713-4e24-aa81-1924f0fbc71c",
    "asset_id": "09b3dbe7-31be-455e-85f0-55da26006efc",
        "dandi:sha2-256": "e6c3783e310781830840e4427cf00f093846d1d96b8806bee5f0821752f0f47b"
    "asset_id": "01511625-2129-46a1-b354-d7cde490021b",
        "dandi:sha2-256": "6d4f8de65f7347464d85a438e1217f84bf15ce8d999894de0d0db77174b95f62"
    "asset_id": "a10eba46-1fdb-4d93-b659-875d7e1c9188",
        "dandi:sha2-256": "431c86f5253276b3cf5ae21b3de9a790281ed6d47b09800025624336ac503420"
    "asset_id": "f359e5a3-3c29-458c-a743-e23fac1596b6",
        "dandi:sha2-256": "6c87a9db4363fded73d7c523543d98c66590fccace10c2a4cda1d3f538c77230"
    "asset_id": "775a7ebb-eaf2-4b0c-8bcb-627dd28a075f",
        "dandi:sha2-256": "ca35d36fa3f26de4ebe3f484e7cb63a06073a220192efc9484be52b7e3453cb4"
    "asset_id": "3ad01876-1f60-411e-a599-8112d37e49de",
        "dandi:sha2-256": "bb8f50b19f3d95080819796d0a1915180c4e09e0c30bb944fc5fcb903095675f"
    "asset_id": "23f50d9d-7c6e-464f-ac9e-dbd76f79dd12",
        "dandi:sha2-256": "adc6922efd8d35e334844e6c49a7c454986bb6520fc0d4650ad8c84fcaa82867"
    "asset_id": "f1bbaa76-c2bb-46b6-a390-31c37fec48fc",
        "dandi:sha2-256": "ec1f01f1ba3788825565134442a2141932ed6fe1249d46308cc4a95f611ee399"
    "asset_id": "6612888c-4e8d-4517-8aff-ddf42fd31f2f",
        "dandi:sha2-256": "3da535205bc2c063f8b1340a8994260a72880f26435641ec0dfb3d2594cf7069"
    "asset_id": "e77fb379-4f6e-4fb6-8500-274e432be169",
        "dandi:sha2-256": "a2f5373bcecae736e20a1de9064f68c7e1b3d46f73fecbedbfb0a8402ae6edfc"
```

<details>
<summary>or in particular for that problematic one a full dump of the record:</summary> 

```shell
$> dandi ls -f json_pp --metadata assets dandi://dandi/000288@draft/sub-H19.03.316/sub-H19.03.316_ses-914342344_icephys.nwb
2022-07-05 15:28:15,089 [ WARNING] A newer version (0.43.0) of dandi/dandi-cli is available. You are using 0.39.6+32.g9f82246
[
  {
    "asset_id": "0d7724de-65fe-447d-ae17-ffaed6306eaa",
    "blob": "486caf5e-6382-46cd-a5ab-6a4cd23c9510",
    "created": "2022-07-01T22:39:06.989063+00:00",
    "metadata": {
      "@context": "https://raw.githubusercontent.com/dandi/schema/master/releases/0.6.3/context.json",
      "access": [
        {
          "schemaKey": "AccessRequirements",
          "status": "dandi:OpenAccess"
        }
      ],
      "approach": [
        {
          "name": "electrophysiological approach",
          "schemaKey": "ApproachType"
        }
      ],
      "blobDateModified": "2022-07-01T15:14:20.305725-07:00",
      "contentSize": 40190924,
      "contentUrl": [
        "https://api.dandiarchive.org/api/assets/0d7724de-65fe-447d-ae17-ffaed6306eaa/download/",
        "https://dandiarchive.s3.amazonaws.com/blobs/486/caf/486caf5e-6382-46cd-a5ab-6a4cd23c9510"
      ],
      "dateModified": "2022-07-01T15:38:55.968509-07:00",
      "digest": {
        "dandi:dandi-etag": "734c031e14b6b308e0dc13af9befd4e4-1"
      },
      "encodingFormat": "application/x-nwb",
      "id": "dandiasset:0d7724de-65fe-447d-ae17-ffaed6306eaa",
      "identifier": "0d7724de-65fe-447d-ae17-ffaed6306eaa",
      "measurementTechnique": [
        {
          "name": "voltage clamp technique",
          "schemaKey": "MeasurementTechniqueType"
        },
        {
          "name": "analytical technique",
          "schemaKey": "MeasurementTechniqueType"
        },
        {
          "name": "current clamp technique",
          "schemaKey": "MeasurementTechniqueType"
        }
      ],
      "path": "sub-H19.03.316/sub-H19.03.316_ses-914342344_icephys.nwb",
      "schemaKey": "Asset",
      "schemaVersion": "0.6.3",
      "variableMeasured": [
        {
          "schemaKey": "PropertyValue",
          "value": "VoltageClampSeries"
        },
        {
          "schemaKey": "PropertyValue",
          "value": "CurrentClampStimulusSeries"
        },
        {
          "schemaKey": "PropertyValue",
          "value": "ProcessingModule"
        },
        {
          "schemaKey": "PropertyValue",
          "value": "CurrentClampSeries"
        },
        {
          "schemaKey": "PropertyValue",
          "value": "VoltageClampStimulusSeries"
        }
      ],
      "wasAttributedTo": [
        {
          "age": {
            "schemaKey": "PropertyValue",
            "unitText": "ISO-8601 duration",
            "value": "P9125.0D",
            "valueReference": {
              "schemaKey": "PropertyValue",
              "value": "dandi:BirthReference"
            }
          },
          "genotype": "",
          "identifier": "907501068",
          "schemaKey": "Participant",
          "sex": {
            "identifier": "http://purl.obolibrary.org/obo/PATO_0000383",
            "name": "Female",
            "schemaKey": "SexType"
          },
          "species": {
            "identifier": "http://purl.obolibrary.org/obo/NCBITaxon_9606",
            "name": "Homo sapiens - Human",
            "schemaKey": "SpeciesType"
          }
        }
      ],
      "wasGeneratedBy": [
        {
          "description": "PLACEHOLDER",
          "identifier": "914342344",
          "name": "914342344",
          "schemaKey": "Session",
          "startDate": "2019-07-30T20:04:18.786000+00:00"
        },
        {
          "description": "Metadata generated by DANDI cli",
          "id": "urn:uuid:fb9908b3-1dc5-489a-905a-5a0c10c8c976",
          "name": "Metadata generation",
          "schemaKey": "Activity",
          "wasAssociatedWith": [
            {
              "identifier": "RRID:SCR_019009",
              "name": "DANDI Command Line Interface",
              "schemaKey": "Software",
              "url": "https://github.com/dandi/dandi-cli",
              "version": "0.41.0+5.g259ae0d"
            }
          ]
        }
      ]
    },
    "modified": "2022-07-01T22:39:07.842331+00:00",
    "path": "sub-H19.03.316/sub-H19.03.316_ses-914342344_icephys.nwb",
    "size": 40190924
  }
]

```
</details>
so can see it having only

```
      "digest": {
        "dandi:dandi-etag": "734c031e14b6b308e0dc13af9befd4e4-1"
      },
```

**Comment by mvandenburgh** [comment]
I suspect this is happening because we're hitting the maximum queue size (100,000 messages) for our CloudAMQP queue. The changes introduced in #1139 made it so each asset validation gets dispatched as a task to the queue, which could potentially have caused our queue to exceed 100,000 messages at a given time. To fix this we'll need to either bump up our CloudAMQP to the next tier, or redesign the way we're doing asset validation so that all assets can be validated in a single task without overloading the worker memory.
