### ISSUE TITLE
in development environment, cannot create new user

### ISSUE THREAD

**Issue by magland** [dandi/dandi-archive#1665]
Trying to run a development environment locally. Using docker-compose. Everything worked up to the point of trying to create a new user... I get the following error

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/api/users/questionnaire-form/?redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&client_id=Dk0zosgt1GAAKfN8LT4STJmLJXwMDPbYWYzfNtAl&response_type=code&state=BGqsEAKwL3&response_mode=query&code_challenge=esSeVJEt_vqJgRGc726tj5m5bGYkoT0lP6hVuDoY4RE&code_challenge_method=S256&QUESTIONS=[%7B%22question%22:%20%22First%20Name%22,%20%22max_length%22:%20100%7D,%20%7B%22question%22:%20%22Last%20Name%22,%20%22max_length%22:%20100%7D]

Django Version: 4.1.10
Python Version: 3.10.12
Installed Applications:
['dandiapi.analytics.apps.AnalyticsConfig',
 'dandiapi.api.apps.PublishConfig',
 'dandiapi.search.apps.SearchConfig',
 'dandiapi.zarr.apps.ZarrConfig',
 'auth_style',
 'django.contrib.admin',
 'composed_configuration._allauth_support.apps.AllauthSupportConfig',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.humanize',
 'django.contrib.sites',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'django.contrib.postgres',
 'whitenoise.runserver_nostatic',
 'django.contrib.staticfiles',
 'corsheaders',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'oauth2_provider',
 'drf_yasg',
 'django_extensions',
 'girder_utils',
 'debug_toolbar',
 'guardian',
 'allauth.socialaccount.providers.github']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/django-project/dandiapi/api/views/auth.py", line 94, in user_questionnaire_form_view
    user_metadata: UserMetadata = user.metadata
  File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 268, in inner
    return func(_wrapped, *args)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 463, in __get__
    raise self.RelatedObjectDoesNotExist(

Exception Type: RelatedObjectDoesNotExist at /api/users/questionnaire-form/
Exception Value: User has no metadata.
```

**Comment by magland** [comment]
Nevermind, I don't need this feature anymore. Feel free to reopen if appropriate.
