### ISSUE TITLE
started to get 503 for awhile for GET https://api.dandiarchive.org/api/dandisets/

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#840]
Happened twice recently

<details>
<summary>Sat, 22 Jan 2022 05:19:00 -0500</summary> 

```shell
Date: Sat, 22 Jan 2022 05:19:00 -0500
From: Cron Daemon <root@drogon.datalad.org>
To: dandi@drogon.datalad.org
Subject: Cron <dandi@drogon> chronic flock -E 0 -e -n /home/dandi/.run/backup2datalad-cron.lock bash -c '/mnt/backup/dandi/dandisets/tools/backups2datalad-cron'

>> python -m tools.backups2datalad -l WARNING -J 5 --target /mnt/backup/dandi/dandisets update-from-backup --backup-remote dandi-dandisets-dropbox --gh-org dandisets
2022-01-22T05:12:37-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-22T05:13:08-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-22T05:13:40-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-22T05:14:13-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-22T05:14:46-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-22T05:15:20-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-22T05:15:55-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-22T05:16:31-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-22T05:17:08-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-22T05:17:48-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-22T05:18:30-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-22T05:19:00-0500 [ERROR   ] dandi HTTP connection failed
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 214, in request
    for i, attempt in enumerate(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/tenacity/__init__.py", line 400, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/tenacity/__init__.py", line 378, in iter
    raise retry_exc.reraise()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/tenacity/__init__.py", line 206, in reraise
    raise self.last_attempt.result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 242, in request
    result.raise_for_status()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.dandiarchive.org/api/dandisets/
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 189, in <module>
    main()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 139, in update_from_backup
    datasetter.update_from_backup(dandisets, exclude=exclude, gh_org=gh_org)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 60, in update_from_backup
    for d in self.get_dandisets(dandiset_ids, exclude=exclude):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 205, in get_dandisets
    for d in diter:
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 204, in <genexpr>
    diter = (d.for_version("draft") for d in self.dandi_client.get_dandisets())
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 490, in get_dandisets
    for data in self.paginate("/dandisets/"):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 336, in paginate
    r = self.get(path, params=params, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 294, in get
    return self.request("GET", path, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 214, in request
    for i, attempt in enumerate(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/tenacity/__init__.py", line 400, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/tenacity/__init__.py", line 378, in iter
    raise retry_exc.reraise()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/tenacity/__init__.py", line 206, in reraise
    raise self.last_attempt.result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 242, in request
    result.raise_for_status()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.dandiarchive.org/api/dandisets/

```
</details>

<details>
<summary>Mon, 24 Jan 2022 04:19:00 -0500</summary> 

```shell
Date: Mon, 24 Jan 2022 04:19:00 -0500
From: Cron Daemon <root@drogon.datalad.org>
To: dandi@drogon.datalad.org
Subject: Cron <dandi@drogon> chronic flock -E 0 -e -n /home/dandi/.run/backup2datalad-cron.lock bash -c '/mnt/backup/dandi/dandisets/tools/backups2datalad-cron'

>> python -m tools.backups2datalad -l WARNING -J 5 --target /mnt/backup/dandi/dandisets update-from-backup --backup-remote dandi-dandisets-dropbox --gh-org dandisets
2022-01-24T04:12:37-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-24T04:13:08-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-24T04:13:40-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-24T04:14:13-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-24T04:14:46-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-24T04:15:20-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-24T04:15:55-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-24T04:16:31-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-24T04:17:08-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-24T04:17:48-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-24T04:18:30-0500 [WARNING ] dandi Retrying GET https://api.dandiarchive.org/api/dandisets/
2022-01-24T04:19:00-0500 [ERROR   ] dandi HTTP connection failed
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 214, in request
    for i, attempt in enumerate(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/tenacity/__init__.py", line 400, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/tenacity/__init__.py", line 378, in iter
    raise retry_exc.reraise()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/tenacity/__init__.py", line 206, in reraise
    raise self.last_attempt.result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 242, in request
    result.raise_for_status()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.dandiarchive.org/api/dandisets/
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 189, in <module>
    main()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 139, in update_from_backup
    datasetter.update_from_backup(dandisets, exclude=exclude, gh_org=gh_org)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 60, in update_from_backup
    for d in self.get_dandisets(dandiset_ids, exclude=exclude):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 205, in get_dandisets
    for d in diter:
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 204, in <genexpr>
    diter = (d.for_version("draft") for d in self.dandi_client.get_dandisets())
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 490, in get_dandisets
    for data in self.paginate("/dandisets/"):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 336, in paginate
    r = self.get(path, params=params, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 294, in get
    return self.request("GET", path, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 214, in request
    for i, attempt in enumerate(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/tenacity/__init__.py", line 400, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/tenacity/__init__.py", line 378, in iter
    raise retry_exc.reraise()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/tenacity/__init__.py", line 206, in reraise
    raise self.last_attempt.result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 242, in request
    result.raise_for_status()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.dandiarchive.org/api/dandisets/


```
</details>

I wonder if anything on the server side which is known about those incidents?

**Comment by waxlamp** [comment]
Did it show up in Sentry?

I vote to close the issue and re-examine if it recurs. @yarikoptic, please re-open the issue if you disagree.

**Comment by yarikoptic** [comment]
I will reopen upon any new occurrence.  A worrying sign that it was failing for quite a while each time according to the number of retries.  heroku or our server -- something seem was quite unreliable at those moments.

**Comment by waxlamp** [comment]
Such is indeed the nature of cloud services 😟
