### ISSUE TITLE
errors in console when loading landing page of any dandiset

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#929]
logout, go to public dandisets, clear console,  and load any dandiset

(there is no apparent bug visually, but console errors would be good to remove)

<details> <summary> console errors </summary>

```
instrument.js:109 TypeError: Cannot read properties of null (reading 'admin')
    at o.<anonymous> (DandisetOwners.vue:111:26)
    at nr.get (vue.runtime.esm.js:4479:25)
    at nr.evaluate (vue.runtime.esm.js:4584:21)
    at e.a [as value] (vue-composition-api.esm.js:1154:27)
    at o.get [as manageOwnersDisabled] (vue-composition-api.esm.js:1365:53)
    at fn (DandisetOwners.vue?e581:3:48)
    at Object.r [as activator] (vue.runtime.esm.js:2590:37)
    at T (helpers.ts:392:12)
    at o.genActivator (index.ts:81:20)
    at o.render (VDialog.ts:326:8)
    at vue-composition-api.esm.js:1494:80
    at $e (vue-composition-api.esm.js:1454:16)
    at o.t.render (vue-composition-api.esm.js:1494:24)
    at o.e._render (vue.runtime.esm.js:3548:22)
    at o.r (vue.runtime.esm.js:4066:21)
    at nr.get (vue.runtime.esm.js:4479:25)
    at new nr (vue.runtime.esm.js:4468:12)
    at Mn (vue.runtime.esm.js:4073:3)
    at o._r.$mount (vue.runtime.esm.js:8415:10)
    at init (vue.runtime.esm.js:3118:13)
    at p (vue.runtime.esm.js:5978:9)
    at d (vue.runtime.esm.js:5925:9)
    at b (vue.runtime.esm.js:6053:9)
    at d (vue.runtime.esm.js:5954:9)
    at b (vue.runtime.esm.js:6053:9)
    at d (vue.runtime.esm.js:5954:9)
    at o.__patch__ (vue.runtime.esm.js:6477:7)
    at o.Pn.e._update (vue.runtime.esm.js:3945:19)
    at o.r (vue.runtime.esm.js:4066:10)
    at nr.get (vue.runtime.esm.js:4479:25)
    at new nr (vue.runtime.esm.js:4468:12)
    at Mn (vue.runtime.esm.js:4073:3)
    at o._r.$mount (vue.runtime.esm.js:8415:10)
    at init (vue.runtime.esm.js:3118:13)
    at p (vue.runtime.esm.js:5978:9)
    at d (vue.runtime.esm.js:5925:9)
    at o.__patch__ (vue.runtime.esm.js:6477:7)
    at o.Pn.e._update (vue.runtime.esm.js:3945:19)
    at o.r (vue.runtime.esm.js:4066:10)
    at nr.get (vue.runtime.esm.js:4479:25)
    at new nr (vue.runtime.esm.js:4468:12)
    at Mn (vue.runtime.esm.js:4073:3)
    at o._r.$mount (vue.runtime.esm.js:8415:10)
    at init (vue.runtime.esm.js:3118:13)
    at p (vue.runtime.esm.js:5978:9)
    at d (vue.runtime.esm.js:5925:9)
    at b (vue.runtime.esm.js:6053:9)
    at d (vue.runtime.esm.js:5954:9)
    at o.__patch__ (vue.runtime.esm.js:6477:7)
    at o.Pn.e._update (vue.runtime.esm.js:3945:19)
(anonymous) @ instrument.js:109
_options.Vue.config.errorHandler @ vue.js:278
rt @ vue.runtime.esm.js:1870
tt @ vue.runtime.esm.js:1839
e._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
Mn @ vue.runtime.esm.js:4073
_r.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
b @ vue.runtime.esm.js:6053
d @ vue.runtime.esm.js:5954
b @ vue.runtime.esm.js:6053
d @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6477
Pn.e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
Mn @ vue.runtime.esm.js:4073
_r.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6477
Pn.e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
Mn @ vue.runtime.esm.js:4073
_r.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
b @ vue.runtime.esm.js:6053
d @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6477
Pn.e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
Mn @ vue.runtime.esm.js:4073
_r.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
b @ vue.runtime.esm.js:6053
d @ vue.runtime.esm.js:5954
b @ vue.runtime.esm.js:6053
d @ vue.runtime.esm.js:5954
b @ vue.runtime.esm.js:6053
d @ vue.runtime.esm.js:5954
E @ vue.runtime.esm.js:6216
D @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
Pn.e._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Xn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ut @ vue.runtime.esm.js:1906
Promise.then (async)
at @ vue.runtime.esm.js:1933
pt @ vue.runtime.esm.js:1990
er @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
me.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
setDandiset @ dandiset.ts:64
(anonymous) @ vuex.esm.js:844
(anonymous) @ vuex.esm.js:466
(anonymous) @ vuex.esm.js:465
g._withCommit @ vuex.esm.js:624
g.commit @ vuex.esm.js:464
commit @ vuex.esm.js:409
i.commit @ vuex.esm.js:796
e.<computed> @ direct-vuex.esm.js:135
(anonymous) @ dandiset.ts:118
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
fetchDandiset @ dandiset.ts:109
(anonymous) @ vuex.esm.js:851
g.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
A.e.<computed> @ direct-vuex.esm.js:176
(anonymous) @ DandisetLandingView.vue:109
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
d @ vue-composition-api.esm.js:1022
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
e.$watch @ vue.runtime.esm.js:4946
Ce @ vue-composition-api.esm.js:952
Ee @ vue-composition-api.esm.js:1028
Ae @ vue-composition-api.esm.js:1107
setup @ DandisetLandingView.vue:103
(anonymous) @ vue-composition-api.esm.js:1741
(anonymous) @ vue-composition-api.esm.js:1527
$e @ vue-composition-api.esm.js:1454
n @ vue-composition-api.esm.js:1525
t.data @ vue-composition-api.esm.js:1509
cr @ vue.runtime.esm.js:4748
sr @ vue.runtime.esm.js:4705
ar @ vue.runtime.esm.js:4642
e._init @ vue.runtime.esm.js:5006
o @ vue.runtime.esm.js:5154
an @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
n @ vue.runtime.esm.js:3301
p @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
E @ vue.runtime.esm.js:6216
D @ vue.runtime.esm.js:6319
E @ vue.runtime.esm.js:6193
D @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
Pn.e._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Xn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ut @ vue.runtime.esm.js:1906
Promise.then (async)
at @ vue.runtime.esm.js:1933
pt @ vue.runtime.esm.js:1990
er @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
me.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ vue-router.esm.js:2989
(anonymous) @ vue-router.esm.js:2988
tt.updateRoute @ vue-router.esm.js:2409
(anonymous) @ vue-router.esm.js:2263
(anonymous) @ vue-router.esm.js:2397
r @ vue-router.esm.js:2001
r @ vue-router.esm.js:2008
$e @ vue-router.esm.js:2012
(anonymous) @ vue-router.esm.js:2392
r @ vue-router.esm.js:2001
(anonymous) @ vue-router.esm.js:2005
(anonymous) @ vue-router.esm.js:2379
(anonymous) @ vue-router.esm.js:2162
p @ vue-router.esm.js:2357
r @ vue-router.esm.js:2004
r @ vue-router.esm.js:2008
r @ vue-router.esm.js:2008
$e @ vue-router.esm.js:2012
tt.confirmTransition @ vue-router.esm.js:2387
tt.transitionTo @ vue-router.esm.js:2260
t.push @ vue-router.esm.js:2704
xt.push @ vue-router.esm.js:3023
b @ vue-router.esm.js:1139
nt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Zi.a._wrapper @ vue.runtime.esm.js:6917
r @ helpers.js:72
Show 120 more frames
fetch.js:122          POST https://o308436.ingest.sentry.io/api/5196549/store/?sentry_key=425b9a012300493d867e97785fae7b88&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.js:122
e @ syncpromise.js:78
t._sendRequest @ fetch.js:121
t.sendEvent @ fetch.js:84
e.sendEvent @ basebackend.js:33
e._sendEvent @ baseclient.js:364
t._sendEvent @ client.js:70
(anonymous) @ baseclient.js:435
onfulfilled @ syncpromise.js:137
(anonymous) @ syncpromise.js:66
_executeHandlers @ syncpromise.js:59
_attachHandler @ syncpromise.js:50
(anonymous) @ syncpromise.js:127
e @ syncpromise.js:78
e.then @ syncpromise.js:126
e._processEvent @ baseclient.js:427
e._captureEvent @ baseclient.js:373
(anonymous) @ baseclient.js:66
onfulfilled @ syncpromise.js:137
(anonymous) @ syncpromise.js:66
_executeHandlers @ syncpromise.js:59
_attachHandler @ syncpromise.js:50
(anonymous) @ syncpromise.js:127
e @ syncpromise.js:78
e.then @ syncpromise.js:126
e.captureException @ baseclient.js:66
e._invokeClient @ hub.js:375
e.captureException @ hub.js:137
(anonymous) @ vue.js:266
e.withScope @ hub.js:89
(anonymous) @ vue.js:264
r @ helpers.js:72
setTimeout (async)
(anonymous) @ trycatch.js:86
_options.Vue.config.errorHandler @ vue.js:263
rt @ vue.runtime.esm.js:1870
tt @ vue.runtime.esm.js:1839
e._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
Mn @ vue.runtime.esm.js:4073
_r.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
b @ vue.runtime.esm.js:6053
d @ vue.runtime.esm.js:5954
b @ vue.runtime.esm.js:6053
d @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6477
Pn.e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
Mn @ vue.runtime.esm.js:4073
_r.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6477
Pn.e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
Mn @ vue.runtime.esm.js:4073
_r.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
b @ vue.runtime.esm.js:6053
d @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6477
Pn.e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
Mn @ vue.runtime.esm.js:4073
_r.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
b @ vue.runtime.esm.js:6053
d @ vue.runtime.esm.js:5954
b @ vue.runtime.esm.js:6053
d @ vue.runtime.esm.js:5954
b @ vue.runtime.esm.js:6053
d @ vue.runtime.esm.js:5954
E @ vue.runtime.esm.js:6216
D @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
Pn.e._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Xn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ut @ vue.runtime.esm.js:1906
Promise.then (async)
at @ vue.runtime.esm.js:1933
pt @ vue.runtime.esm.js:1990
er @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
me.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
setDandiset @ dandiset.ts:64
(anonymous) @ vuex.esm.js:844
(anonymous) @ vuex.esm.js:466
(anonymous) @ vuex.esm.js:465
g._withCommit @ vuex.esm.js:624
g.commit @ vuex.esm.js:464
commit @ vuex.esm.js:409
i.commit @ vuex.esm.js:796
e.<computed> @ direct-vuex.esm.js:135
(anonymous) @ dandiset.ts:118
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
fetchDandiset @ dandiset.ts:109
(anonymous) @ vuex.esm.js:851
g.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
A.e.<computed> @ direct-vuex.esm.js:176
(anonymous) @ DandisetLandingView.vue:109
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
d @ vue-composition-api.esm.js:1022
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
e.$watch @ vue.runtime.esm.js:4946
Ce @ vue-composition-api.esm.js:952
Ee @ vue-composition-api.esm.js:1028
Ae @ vue-composition-api.esm.js:1107
setup @ DandisetLandingView.vue:103
(anonymous) @ vue-composition-api.esm.js:1741
(anonymous) @ vue-composition-api.esm.js:1527
$e @ vue-composition-api.esm.js:1454
n @ vue-composition-api.esm.js:1525
t.data @ vue-composition-api.esm.js:1509
cr @ vue.runtime.esm.js:4748
sr @ vue.runtime.esm.js:4705
ar @ vue.runtime.esm.js:4642
e._init @ vue.runtime.esm.js:5006
o @ vue.runtime.esm.js:5154
an @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
n @ vue.runtime.esm.js:3301
p @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
E @ vue.runtime.esm.js:6216
D @ vue.runtime.esm.js:6319
E @ vue.runtime.esm.js:6193
D @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
Pn.e._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Xn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ut @ vue.runtime.esm.js:1906
Promise.then (async)
at @ vue.runtime.esm.js:1933
pt @ vue.runtime.esm.js:1990
er @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
me.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ vue-router.esm.js:2989
(anonymous) @ vue-router.esm.js:2988
tt.updateRoute @ vue-router.esm.js:2409
(anonymous) @ vue-router.esm.js:2263
(anonymous) @ vue-router.esm.js:2397
r @ vue-router.esm.js:2001
r @ vue-router.esm.js:2008
$e @ vue-router.esm.js:2012
(anonymous) @ vue-router.esm.js:2392
r @ vue-router.esm.js:2001
(anonymous) @ vue-router.esm.js:2005
(anonymous) @ vue-router.esm.js:2379
(anonymous) @ vue-router.esm.js:2162
p @ vue-router.esm.js:2357
r @ vue-router.esm.js:2004
r @ vue-router.esm.js:2008
r @ vue-router.esm.js:2008
$e @ vue-router.esm.js:2012
tt.confirmTransition @ vue-router.esm.js:2387
tt.transitionTo @ vue-router.esm.js:2260
t.push @ vue-router.esm.js:2704
xt.push @ vue-router.esm.js:3023
b @ vue-router.esm.js:1139
nt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Zi.a._wrapper @ vue.runtime.esm.js:6917
r @ helpers.js:72
Show 152 more frames
instrument.js:109 TypeError: Cannot read properties of null (reading 'admin')
    at o.<anonymous> (DandisetOwners.vue:111:26)
    at nr.get (vue.runtime.esm.js:4479:25)
    at nr.evaluate (vue.runtime.esm.js:4584:21)
    at e.a [as value] (vue-composition-api.esm.js:1154:27)
    at o.get [as manageOwnersDisabled] (vue-composition-api.esm.js:1365:53)
    at fn (DandisetOwners.vue?e581:3:48)
    at Object.r [as activator] (vue.runtime.esm.js:2590:37)
    at T (helpers.ts:392:12)
    at o.genActivator (index.ts:81:20)
    at o.render (VDialog.ts:326:8)
    at vue-composition-api.esm.js:1494:80
    at $e (vue-composition-api.esm.js:1454:16)
    at o.t.render (vue-composition-api.esm.js:1494:24)
    at o.e._render (vue.runtime.esm.js:3548:22)
    at o.r (vue.runtime.esm.js:4066:21)
    at nr.get (vue.runtime.esm.js:4479:25)
    at nr.run (vue.runtime.esm.js:4554:22)
    at Xn (vue.runtime.esm.js:4310:13)
    at Array.<anonymous> (vue.runtime.esm.js:1980:12)
    at ut (vue.runtime.esm.js:1906:12)
(anonymous) @ instrument.js:109
_options.Vue.config.errorHandler @ vue.js:278
rt @ vue.runtime.esm.js:1870
tt @ vue.runtime.esm.js:1839
e._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Xn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ut @ vue.runtime.esm.js:1906
Promise.then (async)
at @ vue.runtime.esm.js:1933
pt @ vue.runtime.esm.js:1990
er @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
me.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
setOwners @ dandiset.ts:70
(anonymous) @ vuex.esm.js:844
(anonymous) @ vuex.esm.js:466
(anonymous) @ vuex.esm.js:465
g._withCommit @ vuex.esm.js:624
g.commit @ vuex.esm.js:464
commit @ vuex.esm.js:409
i.commit @ vuex.esm.js:796
e.<computed> @ direct-vuex.esm.js:135
(anonymous) @ dandiset.ts:145
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
fetchOwners @ dandiset.ts:139
(anonymous) @ vuex.esm.js:851
g.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
i.dispatch @ vuex.esm.js:779
A.e.<computed> @ direct-vuex.esm.js:176
(anonymous) @ dandiset.ts:95
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
initializeDandisets @ dandiset.ts:88
(anonymous) @ vuex.esm.js:851
g.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
A.e.<computed> @ direct-vuex.esm.js:176
(anonymous) @ DandisetLandingView.vue:99
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
x @ vue-composition-api.esm.js:1065
S @ vue-composition-api.esm.js:1074
k @ vue-composition-api.esm.js:1077
e.$watch @ vue.runtime.esm.js:4949
Ee @ vue-composition-api.esm.js:1081
De @ vue-composition-api.esm.js:1128
setup @ DandisetLandingView.vue:96
(anonymous) @ vue-composition-api.esm.js:1741
(anonymous) @ vue-composition-api.esm.js:1527
$e @ vue-composition-api.esm.js:1454
n @ vue-composition-api.esm.js:1525
t.data @ vue-composition-api.esm.js:1509
cr @ vue.runtime.esm.js:4748
sr @ vue.runtime.esm.js:4705
ar @ vue.runtime.esm.js:4642
e._init @ vue.runtime.esm.js:5006
o @ vue.runtime.esm.js:5154
an @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
n @ vue.runtime.esm.js:3301
p @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
E @ vue.runtime.esm.js:6216
D @ vue.runtime.esm.js:6319
E @ vue.runtime.esm.js:6193
D @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
Pn.e._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Xn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ut @ vue.runtime.esm.js:1906
Promise.then (async)
at @ vue.runtime.esm.js:1933
pt @ vue.runtime.esm.js:1990
er @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
me.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ vue-router.esm.js:2989
(anonymous) @ vue-router.esm.js:2988
tt.updateRoute @ vue-router.esm.js:2409
(anonymous) @ vue-router.esm.js:2263
(anonymous) @ vue-router.esm.js:2397
r @ vue-router.esm.js:2001
r @ vue-router.esm.js:2008
$e @ vue-router.esm.js:2012
(anonymous) @ vue-router.esm.js:2392
r @ vue-router.esm.js:2001
(anonymous) @ vue-router.esm.js:2005
(anonymous) @ vue-router.esm.js:2379
(anonymous) @ vue-router.esm.js:2162
p @ vue-router.esm.js:2357
r @ vue-router.esm.js:2004
r @ vue-router.esm.js:2008
r @ vue-router.esm.js:2008
$e @ vue-router.esm.js:2012
tt.confirmTransition @ vue-router.esm.js:2387
tt.transitionTo @ vue-router.esm.js:2260
t.push @ vue-router.esm.js:2704
xt.push @ vue-router.esm.js:3023
b @ vue-router.esm.js:1139
nt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Zi.a._wrapper @ vue.runtime.esm.js:6917
r @ helpers.js:72
Show 84 more frames
fetch.js:122          POST https://o308436.ingest.sentry.io/api/5196549/store/?sentry_key=425b9a012300493d867e97785fae7b88&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
```
</details>

**Comment by waxlamp** [comment]
Not seeing this error anymore--closing (re-open if I am wrong).
